name: 'Deploy to DockerHub'

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Push DEV
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            allow: network.host
            target: dev
            tags: aledefreitas/php-nginx-env:dev

      -
        name: Build and Push PROD
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          allow: network.host
          target: prod
          tags: aledefreitas/php-nginx-env:prod